name: CI for Raveny

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - name: Run Integration Tests
        run: npm test
        env:
          REACT_APP_API_ID: ${{ secrets.REACT_APP_API_ID }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      - name: Cypress run with env
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_REACT_APP_API_ID: ${{ secrets.REACT_APP_API_ID }}
          CYPRESS_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          CYPRESS_REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      # - name: Run E2E Tests
      #   run: npm run test:e2e
      #   env:
      #     REACT_APP_API_ID: ${{ secrets.REACT_APP_API_ID }}
      #     REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      #     REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
